fix String error
#4733 uses ``vformat`` with ``%i``.
this causes error when open project with editor.

```
ERROR: vformat: Condition ' error ' is true. returned: String()
   At: core\variant.cpp:3090
```

because vformat doesn't have %i format.