Fix warning using ERR_FAIL_INDEX on unsigned int
This method starting being used in 079ca220e14669ef7c31c399985cd2c733af15bd,
which now triggers this warning from GCC 10:
```
./core/error_macros.h:151:25: error: comparison of unsigned expression in '< 0' is always false [-Werror=type-limits]
```