Fix building VHACD with GCC 13.
Fixes the following error:
thirdparty/vhacd/inc/vhacdICHull.h:46:31: error: 'uint32_t' does not name a type
   46 |     ICHullError Process(const uint32_t nPointsCH, const double minVolume = 0.0);
      |                               ^~~~~~~~

Note the upstream version of the third party library is not affected.

(cherry picked from commit a648d831a9e4175db3b333e6416e2cf3be9959ef)