Android Editor: Add immersive mode option
This allows using the Android Godot Editor in immersive mode, making the most of available screen space.

Pre-commit hooks were skipped due to the following errors, that, to my knowledge, are outside of the scope of this PR:

ERROR: EditorExportPlugin.xml: Unresolved type reference "EditorExportPlatformAndroid" in method reference "EditorExportPlatformAndroid.gradle_build/use_gradle_build" in method "_get_android_dependencies" description.
ERROR: EditorExportPlugin.xml: Unresolved type reference "EditorExportPlatformAndroid" in method reference "EditorExportPlatformAndroid.gradle_build/use_gradle_build" in method "_get_android_dependencies_maven_repos" description.
ERROR: EditorExportPlugin.xml: Unresolved type reference "EditorExportPlatformAndroid" in method reference "EditorExportPlatformAndroid.gradle_build/use_gradle_build" in method "_get_android_libraries" description.
ERROR: EditorExportPlugin.xml: Unresolved type reference "EditorExportPlatformAndroid" in method reference "EditorExportPlatformAndroid.gradle_build/use_gradle_build" in method "_get_android_manifest_activity_element_contents" description.
ERROR: EditorExportPlugin.xml: Unresolved type reference "EditorExportPlatformAndroid" in method reference "EditorExportPlatformAndroid.gradle_build/use_gradle_build" in method "_get_android_manifest_application_element_contents" description.
ERROR: EditorExportPlugin.xml: Unresolved type reference "EditorExportPlatformAndroid" in method reference "EditorExportPlatformAndroid.gradle_build/use_gradle_build" in method "_get_android_manifest_element_contents" description.