Fix build error C2327 on SelfList<CellData> due to recurring VS bug
This is a recurring VS bug, see issues
https://github.com/godotengine/godot/issues/110124 and
https://github.com/godotengine/godot/issues/117259. VS 2022 is currently
broken (tested on 17.14.25 and 17.14.28), so it's not likely that MS is going
to ever fix it.