Fixes Visual Studio compile error due to pe_bliss
Error: C2039: 'min': is not a member of 'std'
Reason: #2518 introduced pe_bliss

Fix: Visual Studio 2015 & 2013 need to include algorithm header before string, otherwise std:min cannot be used.
See: http://stackoverflow.com/questions/17409956