Looks like it is impossible to use child class data from parent constructor, so trying to move to parent::init() function. This still fails with:
In file included from platform\windows\os_windows.h:38:0,
                 from platform\windows\godot_win.cpp:29:
./servers/visual/rasterizer.h:45:35: error: invalid in-class initialization of static data member of non-integral type 'const char*'
  static const char* driver_name = "???";
                                   ^

=====
scons: *** [platform\windows\godot_win.windows.tools.32.o] Error 1