AudioStreamInteractive: Remove transitions for deleted clips
Previously, if a transition was defined for a clip index that was subsequently
removed (by reducing clip_count), an error would be logged when loading the
AudioStreamInteractive:

    ERROR: Condition "p_to_clip < CLIP_ANY || p_to_clip >= clip_count" is true.
       at: add_transition (modules/interactive_music/audio_stream_interactive.cpp:258)

This was because the transition table was not fully updated when reducing
clip_count. Previously any references to the deleted clips as filler clips were
removed, but transitions from or to the deleted clips were not.

Remove any transition table entries that are from or to deleted clips.

Resolves https://github.com/godotengine/godot/issues/95742