Fix getting error message when switching window visibility in editor
Previously, toggling window visibility in the editor gave the following error message:

```
ERROR: Condition "index == -1" is true.
   at: _sub_window_update (scene/main/viewport.cpp:201)
```

This is caused by `old_focus` possibly being the root window.