CI: Hotfix for build error with newer clang++
It will be included in the next release at some point.
- https://github.com/RenderKit/embree/issues 486
  "fix output operator"

[ 30%] Compiling thirdparty/embree/kernels/common/accelset.cpp ...
In file included from thirdparty/embree/kernels/common/device.cpp:12:
In file included from thirdparty/embree/kernels/common/scene_curves.h:10:
thirdparty/embree/kernels/common/../subdiv/bezier_curve.h:138:56:
error: no member named 'u' in 'QuadraticBezierCurve<V>'
  138 |         return cout << "QuadraticBezierCurve ( (" << a.u.lower << ", "
  << a.u.upper << "), " << a.v0 << ", " << a.v1 << ", " << a.v2 << ")";
 ...

(cherry picked from commit c24ea0ecca315676ba31387bf3a277de39ba339a)